### ISSUE TITLE
Items to fix

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#323]
1. be able to add gsoc_year
2. add username to password reset email
3. prepopulate have you partisipated before
4. 'Settings' object has no attribute 'ADMIN_EMAIL' on suborg form since we removed that key
5. github username for org admins/mentors
6. add additional org admins as part of suborg form
7. cut out top part of suborg form
8. make a pr on suborg submit, dont auto commit
9. cookie notice
10. add mentors/suborg admins button
11. add psf privacy policy 
12. checkbox on signing up for PSF terms and another for "opt-in to receive emails"
13. nuke all student users unless they click a link in an email, ie remove email name etc then readd with get request if they click at end of gsoc (gdpr)

**Comment by sounak98** [comment]
- [x] be able to add gsoc_year
- [x] add username to password reset email
- [ ] prepopulate have you partisipated before
- [x] 'Settings' object has no attribute 'ADMIN_EMAIL' on suborg form since we removed that key
- [x] github username for org admins/mentors
- [x] add additional org admins as part of suborg form
- [x] cut out top part of suborg form
- [x] make a pr on suborg submit, dont auto commit
- [x] cookie notice
- [x] add mentors/suborg admins button
- [x] add psf privacy policy
- [x] checkbox on signing up for PSF terms and another for "opt-in to receive emails"
- [x] nuke all student users unless they click a link in an email, ie remove email name etc then readd with get request if they click at end of gsoc (gdpr)
