### ISSUE TITLE
GSoC 2019 - Add theme for blogs

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#52]
This task is to theme the blog pages, as well as the blog posts so that the layout looks in line with the site as well as works on mobile etc.

**Comment by MastersAbh** [comment]
Taking it up @botanicvelious

**Comment by MastersAbh** [comment]
I have added the student blog pages and integrated it on the site. But, currently it displays all the articles, since we do not have any login functionality right now. 
I even made multiple users and added articles with them and it works fine when I hardcode for displaying articles for a particular user. But, the user will be anonymous in our case right now. How should I proceed ?

**Comment by botanicvelious** [comment]
Im not sure what you are asking?

This issue is just to theme the blog pages logins have nothing to do with it?

**Comment by MastersAbh** [comment]
I have queried the model in gsoc app and while querying, it fetches all the articles irrespective of which user has added it and thus, on the student-blogs page, all the articles will be displayed

**Comment by MastersAbh** [comment]
<img width="960" alt="screenshot 3" src="https://user-images.githubusercontent.com/25942597/54048841-e3c0b000-4200-11e9-9a21-eada99f0b98d.png">

I made another user and added an article by that user. But on this page, it displayed all the articles, which shouldn't have been the case if i was logged in as one of the users ??

**Comment by botanicvelious** [comment]
That looks correct, each user will have there own page and all articles will be displayed to everyone.
